django/1027/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("<int:user_pk>/", views.detail, name="detail"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
    path("password/", views.changePassword, name="changePassword"),
    path("delete/", views.delete, name="delete"),
]

django/1027/pjt1027/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("accounts/", include("accounts.urls")),
    path("reviews/", include("reviews.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/1027/reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/comments/", views.comments, name="comments"),
    path("create/", views.create, name="create"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/like/", views.like, name="like"),
    path("category/<str:val>/", views.category, name="category"),
]

django/1027/templates/base.html
{% load bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
      {% bootstrap_css%}
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock css %}
    {% block script %}
      <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
      <script defer="defer" src="{% static 'js/script.js' %}"></script>
    {% endblock script %}
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  </head>

  <body>
    <header>
      <nav class="navbar  navbar-expand-md  navbar-dark bg-dark">
        <div class="container">
          <div>
            <a href="{% url 'index' %}" class="navbar-brand">
              Movie Review
            </a>
          </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class='nav-link' href="{% url 'accounts:detail' request.user.pk %}">{{request.user}}
                  </a>
                </li>
                <li class="nav-item">
                  <a class='nav-link' href="{% url 'accounts:logout' %}">
                    로그아웃
                  </a>
                </li>
              {% else %}
                <li>
                  <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
                </li>
                <li>
                  <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
    {% block indexbody %}{% endblock indexbody %}
    <div class="container">
      {% block content %}{% endblock content %}
    </div>
    {% bootstrap_javascript %}
  </body>

</html>

django/1027/templates/index.html
{% extends 'base.html' %}
{% block indexbody %}

  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://source.unsplash.com/random/800x400" class="d-block w-100" alt="random image">
      </div>
      <div class="carousel-item">
        <img src="https://source.unsplash.com/random/800x400" class="d-block w-100" alt="random image">
      </div>
      <div class="carousel-item">
        <img src="https://source.unsplash.com/random/800x400" class="d-block w-100" alt="random image">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
{% endblock indexbody %}

{% block content %}
  <div>
    <div class="d-flex justify-content-center my-4">
      <a href="{% url 'accounts:index' %}" class="btn btn-outline-success me-3">회원 목록</a>
      <a href="{% url 'reviews:index' %}" class="btn btn-outline-primary">영화 리뷰</a>
    </div>

  </div>
{% endblock content %}