django/1014/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
]

django/1014/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
]

django/1014/reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/detail/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
]

django/1014/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

django/1014/reviews/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.


class Review(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    movie_name = models.CharField(max_length=20)
    grade = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

django/1014/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model=get_user_model()
        fields = ('username', )

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model=get_user_model()
        fields = ('first_name', 'last_name', 'email')

django/1014/reviews/forms.py
from socket import fromshare
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["title", "content", "movie_name", "grade"]

django/1014/accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash

# Create your views here.
@login_required
def index(request):
    users = get_user_model().objects.all()

    context = {
        "users": users,
    }

    return render(request, "accounts/index.html", context)


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:login")
    else:
        form = CustomUserCreationForm()
    context = {"form": form}

    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "reviews:index")
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, "accounts/login.html", context)


def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        "user": user,
    }
    return render(request, "accounts/detail.html", context)


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("accounts:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/password.html", context)


def logout(request):
    auth_logout(request)
    return redirect("reviews:index")


def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("accounts:index")

django/1014/reviews/views.py
from django.shortcuts import render, redirect
from .models import Review
from .forms import ReviewForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    reviews = Review.objects.order_by("-pk")
    context = {
        "reviews": reviews,
    }

    return render(request, "reviews/index.html", context)


@login_required
def create(request):
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("reviews:index")
    else:
        form = ReviewForm()
    context = {
        "form": form,
    }
    return render(request, "reviews/create.html", context)


def detail(request, pk):
    review = Review.objects.get(pk=pk)
    context = {
        "review": review,
    }
    return render(request, "reviews/detail.html", context)


@login_required
def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == "POST":
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect("reviews:detail", review.pk)
    else:
        form = ReviewForm(instance=review)
    context = {
        "form": form,
    }
    return render(request, "reviews/update.html", context)


@login_required
def delete(request, pk):
    reviews = Review.objects.get(pk=pk)
    reviews.delete()
    return redirect("reviews:index")

django/1014/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% block content %}
<p>회원 id: {{ user.username }}</p>
<p>회원 이메일: {{ user.email }}</p>
<p>회원 이름: {{ user.last_name }}{{ user.first_name }}</p>
<p>가입 시간: {{ user.date_joined }}</p>

{% if user == request.user %}
<a href="{% url 'accounts:update' %}" class="btn btn-dark">수정</a>
<a href="{% url 'accounts:delete' %}" class="btn btn-dark">탈퇴</a>
{% endif %}
{% endblock %}

django/1014/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block content %}
<div class='container'>
  <table class='table table-striped'>
    <thead>
      <tr>
        <th scope='col'>회원번호</th>
        <th scope='col'>회원성명</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
      <tr>
        <th scope='row'>{{ user.id }}</th>
        <td>
          <a href="{% url 'accounts:detail' user.pk %}" class="text-decoration-none text-dark fw-bold">
            {{user.username}}</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

django/1014/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<h1>로그인</h1>
<form action='' method='POST'>
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" value="로그인" class="btn btn-dark">
</form>
{% endblock %}

django/1014/accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<h1>비밀번호 변경</h1>
<form action='' method='POST'>
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="btn btn-outline-dark" value="변경">
</form>
{% endblock %}

django/1014/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<h1>회원가입</h1>
<form action='' method='POST'>
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" value="가입하기" class="btn btn-dark">
</form>
{% endblock %}

django/1014/accounts/templates/accounts/update.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<h1>회원정보 수정</h1>
<form action='' method='POST'>
    {% csrf_token %} {% bootstrap_form form %}
    <input type="submit" class="btn btn-outline-dark" value="수정하기">
    <a href="{% url 'accounts:change_password' %}" class="btn btn-dark">비밀번호 변경</a>
</form>
{% endblock %}

django/1014/reviews/templates/reviews/create.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<h1>글 생성</h1>
<form action="" method="POST">
  {% csrf_token %} {% bootstrap_form form %}
  <button type="submit" class="btn btn-dark">제출</button>
</form>
{% endblock %}

django/1014/reviews/templates/reviews/detail.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<h1>글 보기</h1>
<p>글 제목 | {{ review.title }}</p>
<p>작성자 | {{ review.author }}</p>
<p>글 내용 | {{ review.content }}</p>
<p>영화 제목 | {{ review.movie_name }}</p>
<p>영화 평점 | {{ review.grade }}</p>
<p>작성 시간 | {{ review.updated_at }}</p>

<a href="{% url 'reviews:index' %}" class="btn btn-dark">돌아가기</a>
{% if review.author == request.user %}
<span>
  <a href="{% url 'reviews:update' review.pk %}" class="btn btn-dark">수정하기</a>
  <a href="{% url 'reviews:delete' review.pk %}" class="btn btn-dark">삭제하기</a>
</span>
{% endif %}
{% endblock %}

django/1014/reviews/templates/reviews/index.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<div class="container">
    <div class="m-5">
        <div class="d-flex justify-content-center">
            <table class="table text-center align-middle" style="width: 100%">
                <thead>
                    <tr class="p-3 mb-2 bg-dark text-white text-center">
                        <th scope="col">번호</th>
                        <th scope="col">리뷰제목</th>
                        <th scope="col">영화이름</th>
                        <th scope="col">작성자</th>
                        <th scope="col">작성/수정시간</th>
                    </tr>
                </thead>

                <tbody>
                    {% for review in reviews %}
                    <tr class="text-center">
                        <td scope="row">{{ review.pk }}</td>
                        <td>
                            <a href="{% url 'reviews:detail' review.pk %}"
                                class="text-decoration-none text-dark fw-bold">{{ review.title }}</a>
                        </td>
                        <td>{{ review.movie_name }}</td>
                        <td>{{ review.author }}</td>
                        <td>{{ review.updated_at }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

django/1014/reviews/templates/reviews/update.html
{% extends 'base.html' %} {% load django_bootstrap5 %} {% block content %}
<h1>글 수정</h1>
<form action="" method="POST">
  {% csrf_token %} {% bootstrap_form form %}
  <button type="submit" class="btn btn-dark">수정</button>
</form>
{% endblock %}

django/1014/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
        integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
        crossorigin="anonymous"></script>
    <style>
        * {
            font-family: "Noto Sans KR", sans-serif;
        }
    </style>
    <title>Document</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'reviews:index' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'accounts:index' %}">회원 목록</a>
                    </li>
                    {% if user.is_anonymous %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:signup' %}">회원가입</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:login' %}">로그인</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link mx-3" href="{% url 'reviews:create' %}">글 쓰기</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link mx-3" href="{% url 'accounts:logout' %}"> {{user}} 님 로그아웃</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
        integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz"
        crossorigin="anonymous"></script>
</body>

</html>