django/1027/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("<int:user_pk>/", views.detail, name="detail"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
    path("password/", views.changePassword, name="changePassword"),
    path("delete/", views.delete, name="delete"),
]

django/1027/pjt1027/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("accounts/", include("accounts.urls")),
    path("reviews/", include("reviews.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/1027/reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/comments/", views.comments, name="comments"),
    path("create/", views.create, name="create"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/like/", views.like, name="like"),
    path("category/<str:val>/", views.category, name="category"),
]

django/1027/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField("self", symmetrical=False, related_name="followers")
    profile_image = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(100, 100)],
        format="JPEG",
        options={"quality": 80},
    )

    @property
    def full_name(self):
        return f"{self.last_name}{self.first_name}"

django/1027/reviews/models.py
from random import choices
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

CATEGORY_CHOICES = (
    ("2", "국내영화"),
    ("3", "해외영화"),
)

GRADE_CHOICES = (
    (1, "★"),
    (2, "★★"),
    (3, "★★★"),
    (4, "★★★★"),
    (5, "★★★★★"),
)


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    content = models.TextField()
    movie_name = models.CharField(max_length=50)
    grade = models.IntegerField(choices=GRADE_CHOICES, default=5)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_reviews")
    category = models.TextField(choices=CATEGORY_CHOICES, default="2")


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

django/1027/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "profile_image",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "first_name",
            "last_name",
            "email",
            "profile_image",
        )

django/1027/accounts/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.views.decorators.http import require_POST
from .forms import CustomUserCreationForm, CustomUserChangeForm

# Create your views here.


def index(request):
    users = get_user_model().objects.all()
    context = {
        "users": users,
    }
    return render(request, "accounts/index.html", context)


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("accounts:index")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get("next") or "accounts:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


@login_required
def logout(request):
    auth_logout(request)
    messages.warning(request, "로그아웃 되었습니다.")
    return redirect("accounts:index")


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:detail", request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


def detail(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)
    context = {
        "user": user,
    }
    return render(request, "accounts/detail.html", context)


@login_required
@require_POST
def follow(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)
    if request.user == user:
        messages.warning(request, "자신은 팔로우 할 수 없습니다.")
        return redirect("accounts:detail", user_pk)
    if request.user in user.followers.all():
        user.followers.remove(request.user)
        is_follow = False
    else:
        user.followers.add(request.user)
        is_follow = True
    context = {
        "isFollow": is_follow,
        "followers_count": user.followers.count(),
        "followings_count": user.followings.count(),
    }
    return JsonResponse(context)


@login_required
def changePassword(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("accounts:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/changePassword.html", context)


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    messages.warning(request, "탈퇴되었습니다.")
    return redirect("accounts:index")

django/1027/accounts/templates/accounts/changePassword.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <form action="{% url 'accounts:changePassword' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {%bootstrap_button button_type="submit" content="비밀번호 변경하기" %}
  </form>
{% endblock content %}

django/1027/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <div class="m-5 text-center">
    <div class="d-flex justify-content-center align-items-center">
      {% if user.profile_image %}
        <img src="{{ user.profile_image.url }}" class="rounded-circle">
      {% endif %}
      <h1 class="ms-2">{{ user.username }}님의 프로필</h1>
      {% if user.full_name and user.email %}
        <p>{{ user.full_name }}
          |
          {{user.email}}
        </p>
      {% endif %}
    </div>
    <div class="d-flex justify-content-center my-3">
      <div class="text-center me-3">
        <p>팔로워</p>
        <span id="followers-count">{{ user.followers.all|length }}</span>
      </div>
      <div class="text-center">
        <p>팔로잉</p>
        <span id="followings-count">{{ user.followings.all|length }}</span>
      </div>
    </div>
    <div class="ms-3 mt-3">
      {% if request.user != user %}
        <form id="follow-form" data-user-id="{{ user.pk }}">
          {% csrf_token %}
          {% if request.user in user.followers.all %}
            <input type="submit" value="unfollow" class="btn btn-outline-dark">
          {% else %}
            <input type="submit" value="follow" class="btn btn-dark">
          {% endif %}
        </form>
      {% endif %}
    </div>
    {% if request.user == user %}
      <div class="mt-3">
        <a href="{% url 'accounts:update' %} " class='btn btn-outline-primary me-3 '>프로필 수정</a>
        <a href="{% url 'accounts:changePassword' %}" class='btn btn-outline-success me-3'>비밀번호 변경</a>
        <a href="{% url 'accounts:delete' %}" class='btn btn-outline-secondary'>탈퇴</a>
      </div>
    {% endif %}
    <div class="d-flex justify-content-between m-5">
      <div>
        <h4>작성한 글</h4>
        {% for review in user.review_set.all %}
        <a href="{% url 'reviews:detail' review.pk %}">
          <p>{{ forloop.counter}} | {{review.title}}</p>
        </a>
        {% endfor %}
      </div>
      <div>
        <h4>작성한 댓글</h4>
        {% for comment in user.comment_set.all %}
        <a href="{% url 'reviews:detail' comment.review_id %}">
          <p>{{ forloop.counter}} | {{comment.content}}</p>
        </a>
        {% endfor %}
      </div>
      <div>
        <h4>좋아요한 글</h4>
        {% for review in user.like_reviews.all %}
          <a href="{% url 'reviews:detail' review.pk %}">
            <p>{{ forloop.counter}} | {{review.title}}</p>
          </a>
          {% endfor %}
      </div>
    </div>
  </div>


{% endblock content %}

django/1027/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <div class="m-5">
    <ul>
      {% for user in users %}
      <a href="{% url 'accounts:detail' user.pk %}">
        <li class="box p-2 mb-3">
          <p class="d-flex justify-content-between">
              {% if user.profile_image %}
                <img src="{{ user.profile_image.url }}" class="rounded-circle">
              {% endif %}
              <span class="my-auto fs-5 fw-bold">{{user.username}}</span>
              <span>{{user.email}}</span>
              <span>마지막 로그인 시간 | {{user.last_login}}</span>
            </p>
          </li>
        </a>
      {% endfor %}
    </ul>
  </div>
{% endblock content %}

django/1027/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <div>
    <h2>로그인</h2>
    <form action="" method='POST'>
      {% csrf_token %}
      {% bootstrap_form form %}
      {%bootstrap_button button_type="submit" content="로그인" %}
    </form>
  </div>
{% endblock content %}

django/1027/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <div>
    <h3>회원가입</h3>
    <form action="" method="POST" enctype='multipart/form-data'>
      {% csrf_token %}
      {% bootstrap_form form %}
      {%bootstrap_button button_type="submit" content="가입하기" %}
    </form>
  </div>
{% endblock content %}

django/1027/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <div>

    <h1>프로필 수정</h1>
    <form action="" method="POST" enctype='multipart/form-data'>
      {% csrf_token %}
      {% bootstrap_form form %}
      {%bootstrap_button button_type="submit" content="수정하기" %}

    </form>
  </div>
{% endblock content %}