django/1027/pjt1027/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("accounts/", include("accounts.urls")),
    path("reviews/", include("reviews.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/1027/reviews/urls.py
from django.urls import path
from . import views

app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/comments/", views.comments, name="comments"),
    path("create/", views.create, name="create"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/like/", views.like, name="like"),
    path("category/<str:val>/", views.category, name="category"),
]

django/1027/reviews/models.py
from random import choices
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

CATEGORY_CHOICES = (
    ("2", "국내영화"),
    ("3", "해외영화"),
)

GRADE_CHOICES = (
    (1, "★"),
    (2, "★★"),
    (3, "★★★"),
    (4, "★★★★"),
    (5, "★★★★★"),
)


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    content = models.TextField()
    movie_name = models.CharField(max_length=50)
    grade = models.IntegerField(choices=GRADE_CHOICES, default=5)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_reviews")
    category = models.TextField(choices=CATEGORY_CHOICES, default="2")


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

django/1027/reviews/forms.py
from django import forms
from .models import Comment, Review


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)
        labels = {
            "content": "",
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["title", "content", "movie_name", "grade", "category"]

django/1027/reviews/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Review, Comment
from .forms import CommentForm, ReviewForm
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model


def index(request):
    review = Review.objects.all().order_by("-pk")
    context = {"review": review}
    return render(request, "reviews/index.html", context)


def detail(request, pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm()

    context = {
        "review": review,
        "comment_form": comment_form,
    }
    return render(request, "reviews/detail.html", context)


def comments(request, pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
        context = {
            "content": comment.content,
            "userName": comment.user.username,
        }
    return JsonResponse(context)


@login_required
def create(request):
    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            db_review_form = review_form.save(commit=False)
            db_review_form.user = request.user
            db_review_form.save()
            return redirect("reviews:index")
    else:
        review_form = ReviewForm()
    return render(request, "reviews/create.html", {"review_form": review_form})


def update(request, pk):
    db_review_form = Review.objects.get(pk=pk)

    if request.method == "POST":
        review_form = ReviewForm(request.POST, instance=db_review_form)

        if review_form.is_valid():
            review_form.save()

            return redirect("reviews:index")

    else:
        review_form = ReviewForm(instance=db_review_form)

    return render(request, "reviews/create.html", {"review_form": review_form})


def delete(request, pk):
    review = Review.objects.get(pk=pk)
    review.delete()

    return redirect("reviews:index")


@login_required
def like(request, pk):
    review = Review.objects.get(pk=pk)
    # 만약에 로그인한 유저가 이 글을 좋아요를 눌렀다면,
    # if article.like_users.filter(id=request.user.id).exists():
    if request.user in review.like_users.all():
        # 좋아요 삭제하고
        review.like_users.remove(request.user)
    else:
        # 좋아요 추가하고
        review.like_users.add(request.user)
    # 상세 페이지로 redirect
    return redirect("reviews:detail", pk)


def category(request, val):
    if val == "1":
        reviews = Review.objects.all().order_by("-pk")
    elif val == "2":
        reviews = Review.objects.filter(category=val)
    elif val == "3":
        reviews = Review.objects.filter(category=val)
    relist = []
    for r in reviews:
        user = get_user_model().objects.get(pk=r.user_id)
        relist.append(
            {
                "user": user.username,
                "pk": r.pk,
                "title": r.title,
                "content": r.content,
                "movie_name": r.movie_name,
                "grade": r.grade,
                "created_at": r.created_at,
                "updated_at": r.updated_at,
                "category": r.category,
            }
        )
    context = {
        "relist": relist,
    }
    return JsonResponse(context)

django/1027/reviews/templates/reviews/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
{% if request.resolver_match.url_name == 'create' %}
    <h1>생성</h1>
{% else %}
    <h1>수정</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}

    {% bootstrap_form review_form %}

    {% bootstrap_button button_type="submit" content="OK" %}
</form>
{% endblock %}

django/1027/reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load widget_tweaks %}

{% block content %}

  <div class="m-5">
    <h3 class="fw-bold my-3">{{ review.title }}</h3>
    <span class="fs-4">{{ review.content }}</span>
    <span class="float-end">{{ review.user }} | {{ review.updated_at }}</span>
    <p class="mt-5">
      {{ review.movie_name }} | 
      {% for i in ""|ljust:review.grade %}
        <span>★</span>
      {% endfor %} |
    {% if review.category == "2" %}
        국내영화
      {% else %}
        해외영화
      {% endif %}
    </p>
    <div class="text-center my-4">
      {% if request.user.is_authenticated %}
        <a id="like-link" href="{% url 'reviews:like' review.pk %}">
          {% if request.user in review.like_users.all %}
            <i id="like-btn" class="bi bi-heart-fill"></i>
          {% else %}
            <i id="like-btn" class="bi bi-heart"></i>
          {% endif %}
        </a>{{ review.like_users.count }}
      {% endif %}
    </div>
    <div class="text-end">
      <a href="{% url 'reviews:index' %}" class="btn btn-outline-primary">목록으로</a>
      <a href="{% url 'reviews:update' review.pk %}" class="btn btn-outline-success">수정하기</a>
      <a href="{% url 'reviews:delete' review.pk %}" class="btn btn-outline-danger">삭제하기</a>
    </div>
    <hr>
    <h4>댓글</h4>
    {% if request.user.is_authenticated %}
      <div class="mt-3">
        <form id="comment-form" data-review-id="{{ review.pk }}">
          {% csrf_token %}
          <div class=" input-group">
            {%render_field comment_form.content class+="form-control" rows="1" cols="10"%}
            <button class="btn btn-outline-primary" type="submit" id="button-addon2">등록</button>
          </div>
        </form>
      </div>
    {% endif %}
  
    <div id="comments" class="mt-3">
      {% for comment in review.comment_set.all %}
        <div id="comment">
          <span>
            {{ comment.user.username }}
            |
            {{ comment.content }}</span>
          <hr>
        </div>
        {% empty %}
        <p>댓글이 없어요 ㅠ_ㅠ</p>
      {% endfor %}
    </div>
  </div>
  
</div>

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  const commentForm = document.querySelector('#comment-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
  commentForm.addEventListener('submit', function(event) {

    event.preventDefault();
    axios({
      method: 'post',
      url: `/reviews/${event.target.dataset.reviewId}/comments/`,
      headers: {'X-CSRFToken': csrftoken},
      data: new FormData(commentForm) 
    })

    .then(response => {
      const comments = document.querySelector('#comments')
      const span = document.createElement('span')
      span.innerText = `${response.data.userName} | ${response.data.content}`
      const hr = document.createElement('hr')
      comments.append(span)
      comments.append(hr)
      commentForm.reset()
    })
  })
</script>


{% endblock %}

django/1027/reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
<div class="m-5">
  <h2 class="text-center">영화 리뷰</h2>
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    <div class="container">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
  {% endfor %}
  {% endif %}

  <div class="d-flex justify-content-between mt-4">
    <form id="select-form" action="">
      {% csrf_token %}
      <select id="category-sel" class="form-select" onchange="showValue(this)">
        <option selected="selected" value="1">전체</option>
        <option value="2">국내 영화</option>
        <option value="3">해외 영화</option>
      </select>
    </form>
    <a href="{% url 'reviews:create' %}">
      <button type="button" class="btn btn-primary mb-3">리뷰 작성</button>
    </a>
  </div>
  <div>
    <div id="review-box" class="row g-3">
      {% for reviews in review %}
      <a href="{% url 'reviews:detail' reviews.pk %}">
      <div class="col-12 box p-3">
        <h3 class="fw-bold">{{ reviews.title }}</h3>
        <p class="mt-3">
          {{ reviews.user }} | 
          {{ reviews.movie_name }} | 
          {% for i in ""|ljust:reviews.grade %}
            <span>★</span>
          {% endfor %} |
          {% if reviews.category == "2" %}
            국내영화
          {% else %}
            해외영화
          {% endif %}
        </p>
        <p class="text-end">
          {{ reviews.updated_at|date:"Y-m-d" }}
        </p>
      </div>
      </a>
      {% endfor %}
    </div>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  const showValue = (target) => {
    let val = target.value
    axios({
      method: 'get',
      url: `/reviews/category/${target.value}`,
    }).then(response => {
      const reviewBox = document.querySelector('#review-box');
      reviewBox.textContent = "";
      const relist = response.data.relist;

      for (let i = 0; i < relist.length; i++) {
        console.log(relist[i].pk, relist[i].title);
        if (relist[i].grade == 5) {
          var grade = "★★★★★"
        } else if (relist[i].grade == 4) {
          var grade = "★★★★"
        } else if (relist[i].grade == 3) {
          var grade = "★★★"
        } else if (relist[i].grade == 2) {
          var grade = "★★"
        } else if (relist[i].grade == 1) {
          var grade = "★"
        }
        
        if (relist[i].category === "2") {
          var category = "국내영화"
        } else if (relist[i].category === "3") {
          var category = "해외영화"
        }

        let updated_at = new Date(relist[i].updated_at).toLocaleDateString().replace(/\./g, '').split(' ').join('-');
        reviewBox.insertAdjacentHTML('beforeend',
          `
          <a href= "/reviews/${relist[i].pk}">
            <div class="col-12 box p-3">
              <h3 class="fw-bold">${relist[i].title}</h3>
              <p class="mt-3">
                ${relist[i].user} | 
                ${relist[i].movie_name} | 
                <span>${grade}</span> | 
                <span>${category}</span>
              </p>
              <p class="text-end">
                ${updated_at}
              </p>
            </div>
            </a>
          </div>`
        )
      }
    })
  };
</script>
{% endblock %}